name: Code Quality Check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Run Build + Lint + Tests
        run: ./mvnw -B clean verify
